### ISSUE TITLE
ValueError: illegal san:

### ISSUE THREAD

**Issue by KenAijmNight** [EivindKjosbakken/ChessEngine#1]
ValueError: illegal san: 'g1f3' in rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1

How can this be resolved?

**Comment by EivindKjosbakken** [comment]
Hi, thank you for your question. This error seems to be that the move g1f3 is illegal in the position given. I found the board position given the FEN encoding you gave me, and it is the opening chess position as shown in the image below. I suspect the error might be because somehow it has become black turn to play (and not white which should be the case in the opening chess board position). Can you verify that it is whites turn to move? Let me know if this works, and if you have any further questions!
<img width="395" alt="board" src="https://github.com/EivindKjosbakken/ChessEngine/assets/65784136/512bc540-5a9b-4049-a7b2-2646135ae84e">

**Comment by KenAijmNight** [comment]
I indeed fixed it with my own code!
